## Copyright (c) 2022, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Deploy Elasticsearch and Kibana in OCI"
description: "Deploy cluster configuration (simple) of Elasticsearch and Kibana in Oracle Cloud Infrastructure."
stackDescription: "Deploy Elasticsearch and Kibana in OCI"
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release
  - elasticsearch_download_url
  - kibana_download_url
  - logstash_download_url
  - availability_domain_number

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - availability_domain_name
  - show_advanced

- title: "Compute Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - ssh_public_key
  - instance_os
  - linux_os_version
  - instance_shape
  - instance_flex_shape_ocpus
  - instance_flex_shape_memory

- title: "Networking Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:  
  - VCN-CIDR
  - ELKSubnet-CIDR

- title: "ES & Kibana Optional Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - KibanaPort
  - ESDataPort
  - elasticsearch_download_version
  - kibana_download_version
  - logstash_download_version

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Region where you deploy your Elasticsearch and Kibana"
    type: oci:identity:region:name
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment OCID"
    description: "Compartment where you deploy your Elasticsearch and Kibana"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  availability_domain_name:
    title: "Availability Domain Name"
    description: "Availability Domain where you deploy your Elasticsearch and Kibana"
    type: oci:identity:availabilitydomain:name
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}
    visible: complexExpression

  # Optional Configuration 

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false

  instance_os:
    type: enum
    required: false
    visible: true
    title: "Instance OS"
    description: "An Operating System that determines the operating system for your Elasticsearch and Kibana host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: true
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for your Elasticsearch and Kibana host."
    default: "8"
    enum:
      - "8"  

  instance_shape:
    type: oci:core:instanceshape:name
    default: "VM.Standard.E4.Flex"
    title: "ELK Instance Shape"
    description: "ELK Instance Shape"
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.A1.Flex"

  instance_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 15
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape
            - "VM.Standard.E4.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.A1.Flex"

  VCN-CIDR:
    type: string
    required: false
    default: "192.168.0.0/25"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "A single, contiguous IPv4 CIDR block of your choice for the VCN"

  ELKSubnet-CIDR:
    type: string
    required: false
    default: "192.168.0.0/28"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "ELK Subnet CIDR"
    description: "ELK Subnet CIDR"

  elasticsearch_download_url:
    title: "Elasticsearch download URL"
    description: "Elasticsearch download URL"
    type: string
    required: false

  kibana_download_url:
    title: "Kibana download URL"
    description: "Kibana download URL"
    type: string
    required: false

  logstash_download_url:
    title: "Logstash download URL"
    description: "Logstash download URL"
    type: string
    required: false

  KibanaPort:
    title: "Kibana Port"
    description: "Kibana Port"
    type: number
    minimum: 1
    maximum: 65535
    multipleOf: 1
    default: 5601
    required: false
  
  ESDataPort:
    title: "ESData Port"
    description: "Elasticsearch Data Port (Outbound HTTP Traffic)"
    type: number
    minimum: 1
    maximum: 65535
    multipleOf: 1
    default: 9200
    required: false

  elasticsearch_download_version:
    type: enum
    required: false
    visible: true
    title: "Elasticsearch version"
    description: "Choose the Elasticsearch version to install."
    default: "7.16.3"
    enum:
      - "7.16.3"

  kibana_download_version:
    type: enum
    required: false
    visible: true
    title: "Kibana version"
    description: "Choose the Kibana version to install."
    default: "7.16.3"
    enum:
      - "7.16.3"

  logstash_download_version:
    type: enum
    required: false
    visible: true
    title: "Logstash version"
    description: "Choose the Logstash version to install."
    default: "7.16.3"
    enum:
      - "7.16.3"

  release:
    type: string
    required: false
    visible: false
    title: "Reference Architecture Release (OCI Architecture Center)"

outputs:

  ELK_VM_public_IP:
    title: "ELK VM Public IP"
    displayText: "ELK VM Public IP"
    type: copyableString
    visible: true
  
  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: text
    visible: true
  
  

